#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Generate crates/fono-tts/src/supertonic/nfkd_table.rs, the Unicode NFKD
# decomposition table used by the Supertonic TTS text frontend (Slice 2,
# Task 2.3b of plans/2026-07-12-supertonic3-local-tts-engine-v1.md).
#
# Adapted from the upstream sherpa-onnx generator
# (scripts/supertonic/generate_nfkd_table.py, our PR #3750) to emit a Rust
# `const` table instead of a C++ header. Semantics are identical.
#
# Why this exists: the Supertonic reference frontend applies
# unicodedata.normalize("NFKD", text) before mapping characters through the
# unicode indexer, which was itself built from NFKD text. Precomposed
# characters (Romanian ă/ș/ț, Czech č, Polish ą, ...) map to -1 and are
# silently dropped unless decomposed first. This dumps Python's own NFKD data
# for the Basic Multilingual Plane into a compact lookup table so Fono's Rust
# runtime behaves like the reference — without pulling in the
# `unicode-normalization` crate (binary-size budget; see AGENTS.md).
#
# Hangul syllables (U+AC00..U+D7A3) are excluded: they are decomposed
# algorithmically at runtime (see frontend.rs).
#
# Usage:  python3 scripts/gen-supertonic-nfkd-table.py [output.rs]

import sys
import unicodedata
from pathlib import Path

HANGUL_FIRST = 0xAC00
HANGUL_LAST = 0xD7A3


def collect_entries():
    entries = []
    for cp in range(0x10000):
        if HANGUL_FIRST <= cp <= HANGUL_LAST:
            continue
        ch = chr(cp)
        decomposed = unicodedata.normalize("NFKD", ch)
        if decomposed == ch:
            continue
        # Skip the rare mappings that leave the BMP; the runtime only handles
        # 16-bit values (the indexer covers U+0000..U+FFFF).
        if any(ord(c) > 0xFFFF for c in decomposed):
            continue
        entries.append((cp, [ord(c) for c in decomposed]))
    return entries


def format_array(values, per_line=12, indent="    "):
    lines = []
    for i in range(0, len(values), per_line):
        chunk = ", ".join(f"0x{v:04X}" for v in values[i : i + per_line])
        lines.append(f"{indent}{chunk},")
    return "\n".join(lines)


def main():
    script_dir = Path(__file__).resolve().parent
    default_out = (
        script_dir.parent
        / "crates"
        / "fono-tts"
        / "src"
        / "supertonic"
        / "nfkd_table.rs"
    )
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else default_out

    entries = collect_entries()
    entries.sort(key=lambda e: e[0])

    codepoints = [cp for cp, _ in entries]
    offsets = [0]
    pool = []
    for _, decomposed in entries:
        pool.extend(decomposed)
        offsets.append(len(pool))

    if len(pool) > 0xFFFF:
        print("Error: decomposition pool no longer fits in u16 offsets")
        return 1

    unicode_version = unicodedata.unidata_version

    body = f"""// SPDX-License-Identifier: GPL-3.0-only
//! Auto-generated by `scripts/gen-supertonic-nfkd-table.py` from Python's
//! `unicodedata` (Unicode {unicode_version}). DO NOT EDIT BY HAND.
//!
//! NFKD decompositions for the Basic Multilingual Plane, excluding Hangul
//! syllables (U+AC00..U+D7A3), which are decomposed algorithmically in
//! `frontend.rs`. Only included from that module.

/// Codepoints that have an NFKD decomposition, sorted ascending. Binary-search
/// this; the match index `i` selects the pool range
/// `NFKD_OFFSETS[i]..NFKD_OFFSETS[i + 1]`.
pub const NFKD_CODEPOINTS: &[u16] = &[
{format_array(codepoints)}
];

/// `NFKD_OFFSETS[i]..NFKD_OFFSETS[i + 1]` delimits the decomposition of
/// `NFKD_CODEPOINTS[i]` inside `NFKD_POOL`. Length is `NFKD_CODEPOINTS.len() + 1`.
pub const NFKD_OFFSETS: &[u16] = &[
{format_array(offsets)}
];

/// Flat pool of decomposed codepoints, indexed via `NFKD_OFFSETS`.
pub const NFKD_POOL: &[u16] = &[
{format_array(pool)}
];
"""

    out_path.write_text(body, encoding="utf-8")
    print(f"Wrote {len(codepoints)} entries ({len(pool)} pool values) -> {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
